// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdx7rZAFYEBRa-S4P-HtKXpqyhEOlKDiI',
    appId: '1:380611916279:web:1393619decdf910eacfef2',
    messagingSenderId: '380611916279',
    projectId: 'zestinme-8f1bf',
    authDomain: 'zestinme-8f1bf.firebaseapp.com',
    storageBucket: 'zestinme-8f1bf.firebasestorage.app',
    measurementId: 'G-7WPE243640',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfGeQtAEQQocZKMfxUXvoBPBRHUs-WcGk',
    appId: '1:380611916279:android:aa62d79e16f10fa7acfef2',
    messagingSenderId: '380611916279',
    projectId: 'zestinme-8f1bf',
    storageBucket: 'zestinme-8f1bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBsuxCwzcno7HuI8OqMFbBgfMBxVfCy8Q',
    appId: '1:380611916279:ios:d6d859e4f45b8634acfef2',
    messagingSenderId: '380611916279',
    projectId: 'zestinme-8f1bf',
    storageBucket: 'zestinme-8f1bf.firebasestorage.app',
    iosBundleId: 'com.jyoon.zestinme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBsuxCwzcno7HuI8OqMFbBgfMBxVfCy8Q',
    appId: '1:380611916279:ios:d6d859e4f45b8634acfef2',
    messagingSenderId: '380611916279',
    projectId: 'zestinme-8f1bf',
    storageBucket: 'zestinme-8f1bf.firebasestorage.app',
    iosBundleId: 'com.jyoon.zestinme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdx7rZAFYEBRa-S4P-HtKXpqyhEOlKDiI',
    appId: '1:380611916279:web:efeefb6593ee3d7cacfef2',
    messagingSenderId: '380611916279',
    projectId: 'zestinme-8f1bf',
    authDomain: 'zestinme-8f1bf.firebaseapp.com',
    storageBucket: 'zestinme-8f1bf.firebasestorage.app',
    measurementId: 'G-5M23Q3G7FR',
  );

}